[package]
name = "kirje-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
chrono.workspace = true
directories.workspace = true
keyring.workspace = true
kirje-core.workspace = true
kirje-local-io.workspace = true
kirje-protocol.workspace = true
kirje-store.workspace = true
secrecy.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
toml.workspace = true
uuid.workspace = true

[lints]
workspace = true
